version: '3.8'

services:
  postgres_books:
    image: postgres:15-alpine
    container_name: postgres-book
    environment:
      POSTGRES_USER: book_user
      POSTGRES_PASSWORD: book_password
      POSTGRES_DB: book_db
    ports:
      - "5436:5432"
    networks:
      - shared-network

  book-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: book-api
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres_books:5432/book_db
      SPRING_DATASOURCE_USERNAME: book_user
      SPRING_DATASOURCE_PASSWORD: book_password
      KAFKA_BROKERS: kafka:29092
      SPRING_KAFKA_BOOTSTRAP-SERVERS: kafka:29092
      SPRING_KAFKA_PRODUCER_BOOTSTRAP-SERVERS: kafka:29092
    depends_on:
      - postgres_books
    ports:
      - "8006:8006"
    networks:
      - shared-network

networks:
  shared-network:
    external: true

